version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sigamdb
      MYSQL_USER: sigam
      MYSQL_PASSWORD: senha
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql