version: '3.8'

services:
  postgres:
    image: postgres:latest  # Usando a imagem mais recente do PostgreSQL
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: sigam  # Define o usuário do PostgreSQL
      POSTGRES_PASSWORD: senha  # Define a senha do PostgreSQL
      POSTGRES_DB: sigamdb  # Define o nome do banco de dados
    ports:
      - "5433:5432"  # Mapeia a porta do contêiner do PostgreSQL para a porta do host
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  # Mapeia o volume para armazenar os dados do PostgreSQL
